# Generated by Django 5.1.2 on 2024-12-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_alter_book_penerbit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='penerbit',
            field=models.CharField(max_length=50),
        ),
    ]
