# Generated by Django 5.1.2 on 2024-12-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_penerbit', models.CharField(max_length=4)),
                ('nama_penerbit', models.CharField(max_length=100)),
                ('alamat_penerbit', models.CharField(max_length=200)),
                ('kota_penerbit', models.CharField(max_length=50)),
                ('kontak_penerbit', models.CharField(max_length=12)),
                ('email_penerbit', models.CharField(max_length=50)),
            ],
        ),
    ]
